[STock-Broker-App] get-Watchlists API
coditas-eltp-golang-learners-2024/stock_broker_application pull request #14
Opened 2024-05-06 21:43 UTC by PrahladSingh-coditas

### getWatchLists API
The API is working as expected. Taking UserID from the token and displaying the corresponding Watchlist.

Image:

<img width="1440" alt="Screenshot 2024-05-07 at 3 03 34 AM" src="https://github.com/coditas-eltp-golang-learners-2024/stock_broker_application/assets/158143460/0876192b-021d-4aa5-93b3-79a485b49a0e">

2024-05-10 05:26 UTC, Gauravi-S commented on src/app/watchlist/commons/constants/constants.go
> +// authentication NEST API URL Keys
rename to // watchlist NEST API URL Keys

2024-05-10 05:26 UTC, Gauravi-S commented on src/app/watchlist/commons/constants/constants.go
> +    ServiceName        = "authentication"
change authentication to watchlist

2024-05-10 05:26 UTC, Gauravi-S commented on src/app/watchlist/commons/constants/constants.go
> +    PortDefaultValue   = 8080
change port to 8081

2024-05-10 05:38 UTC, Gauravi-S commented on src/app/watchlist/commons/constants/errors.go
> +// Get Watchlist Errors
give comment as // Watchlist Errors

2024-05-10 05:38 UTC, Gauravi-S commented on src/app/watchlist/commons/constants/errors.go
> +	WatchlistNotFound = "watchlist not found"
rename to "WatchlistNotFoundError"

2024-05-10 05:39 UTC, Gauravi-S commented on src/app/watchlist/commons/constants/routes.go
> +// authentication route Constants
replace quthentication to watchlist

2024-05-10 05:42 UTC, Gauravi-S commented on src/app/watchlist/commons/constants/routes.go
> +// getWatchlist route Constants
rename to // Watchlist route constants

2024-05-10 05:57 UTC, Gauravi-S commented on src/app/watchlist/handler/getWatchlistHandler.go
> +// @Summary Retrieve user's watchlist
give proper tag
//@Tags Get the list of WatchLists

2024-05-10 05:59 UTC, Gauravi-S commented on src/app/watchlist/models/getWatchlistModel.go
> +type GetWatchListRequest struct {
rename to GetWatchlistsRequest

2024-05-10 06:00 UTC, Gauravi-S commented on src/app/watchlist/handler/getWatchlistHandler.go
> +package handler
rename file to getWatchlistsHandler.go

2024-05-10 06:00 UTC, Gauravi-S commented on src/app/watchlist/models/getWatchlistModel.go
> +package models
rename file to getWatchlistsModel.go

2024-05-10 06:02 UTC, Gauravi-S commented on src/app/watchlist/repositories/getWatchlistsRepositories.go
> +	if err := repository.DB.Model(&models.TokenData{}).Where("user_id = ?", userID).Find(&watchlistSlice).Error; err != nil {
again, pls define column name in genericConstants and use it here.
add it in already declared const group
// Column Name Constants
const (

2024-05-10 06:08 UTC, Gauravi-S commented on src/app/watchlist/business/getWatchlistsService.go
> +func (repository *getWatchListSercvice) NewGetWatchlistService(ctx *gin.Context) ([]string, error) {
user variable name service instead of repository

2024-05-10 06:11 UTC, Gauravi-S commented on src/app/watchlist/repositories/getWatchlistsRepositories.go
> +	if err := repository.DB.Model(&models.TokenData{}).Where("user_id = ?", userID).Find(&watchlistSlice).Error; err != nil {
again declare column "user_id" name in genericConstants
under already defined const group
// Column Name Constants
const (

2024-05-10 07:01 UTC, Gauravi-S commented on src/app/watchlist/business/getWatchlistsService.go
> +		getWatchlistInterface: userData,
rename getWatchlistInterface to getWatchlistRepository

2024-05-10 07:02 UTC, Gauravi-S commented on src/app/watchlist/business/getWatchlistsService.go
> +func (repository *getWatchListSercvice) NewGetWatchlistService(ctx *gin.Context) ([]string, error) {
use variable name as "service" instead of "repository"

2024-05-10 07:02 UTC, Gauravi-S commented on src/app/watchlist/business/getWatchlistsService.go
> +}
it should be like
service.getWatchlistRepository.GetWatchlists(ctx)

2024-05-10 07:03 UTC, Gauravi-S commented on src/app/watchlist/business/getWatchlistsService.go
> +func NewUsersService(userData repositories.GetWatchlistsRepository) NewGetWatchlistService {
use getWatchlistRepository instead of userData

2024-05-10 07:06 UTC, Gauravi-S commented on src/app/watchlist/handler/getWatchlistHandler.go
> +	if err != nil {
Please handle the error 204: content not found
when there is no watchlist present in the db for user.
can use constants.WatchlistNotFound to log

2024-05-10 07:08 UTC, Gauravi-S commented on src/app/watchlist/handler/getWatchlistHandler.go
> +		context.JSON(http.StatusInternalServerError, gin.H{genericConstants.GenericJSONErrorMessage: constants.WatchlistNotFound})
don't use constants.WatchlistNotFound in internalSever
just return the err
cause it's default error with multiple scenarios
like db connection might fail or some other db data type issue.
we can't say watchlistNotFound in such case.

2024-05-14 12:06 UTC, suman-byakod commented on src/app/watchlist/models/getWatchlistsModel.go
> +	UserId int `json:"userID" validate:"required" example:"5" `
No need of this model. Since you are not using it anywhere.

2024-05-14 12:21 UTC, vipin-raj-coditas requested changes

2024-05-14 12:21 UTC, vipin-raj-coditas commented on src/app/watchlist/main.go
> +// @host localhost:8080
8081

2024-05-14 12:21 UTC, vipin-raj-coditas commented on src/models/genericModels.go
> +}
Remove it

2024-05-15 10:55 UTC, Gauravi-S commented on src/app/watchlist/handler/getWatchlistsHandler.go
> +type NewGetWatchlistController interface {
keep variable name as "GetWatchlists" in plural everywhere

2024-05-15 11:00 UTC, Gauravi-S commented on src/app/watchlist/repositories/getWatchlistsRepositories.go
> +package repositories
rename file to getWatchlistRepository

2024-05-15 11:01 UTC, Gauravi-S commented on src/app/watchlist/repositories/getWatchlistsRepositories.go
> +type userDBRepository struct {
rename userDBRepository to watchlistDBRepository

2024-05-15 12:18 UTC, vipin-raj-coditas commented on src/app/watchlist/handler/getWatchlistsHandler.go
> +	context.JSON(http.StatusOK, gin.H{genericConstants.WatchlistTable: watchlistData})
```suggestion
	context.JSON(http.StatusOK, watchlistData})
```

Can you please try this

2024-05-16 06:18 UTC, Gauravi-S approved these changes

2024-05-16 06:19 UTC, merged