[STOCK-BROKING-APP] - Change Password API
coditas-eltp-golang-learners-2024/stock_broker_application pull request #9
Opened 2024-04-26 07:15 UTC by sanket5577-coditas

**Done with change Password**
<img width="955" alt="MissingToken" src="https://github.com/coditas-eltp-golang-learners-2024/stock_broker_application/assets/158143270/cbf52aad-c0f1-40be-8d91-f5d7b78fa3a0">
<img width="952" alt="changepswdDone" src="https://github.com/coditas-eltp-golang-learners-2024/stock_broker_application/assets/158143270/d89f73c1-9a25-4bd8-8970-ffae53fd5cde">

2024-04-26 11:17 UTC, vipin-raj-coditas commented on .vscode/launch.json
Remove this file

2024-04-26 11:21 UTC, vipin-raj-coditas commented on src/app/authentication/commons/constants/constants.go
> +	EmailId                       = "email"
Create a different Contants for above fields

2024-04-26 11:35 UTC, vipin-raj-coditas commented on src/app/authentication/models/changePasswordModel.go
> +	NewPassword string `gorm:"column:newPassword" json:"newPassword" validate:"required,min=8" example:"newPassword"`
remove gorm from here

2024-04-26 11:37 UTC, vipin-raj-coditas commented on src/app/authentication/models/changePasswordModel.go
> +}
remove this

2024-04-26 12:10 UTC, Gauravi-S commented on src/app/authentication/business/changePasswordService.go
> +	PasswordResetter repositories.AuthenticationProvider
rename to PasswordResetterRepository

2024-04-26 12:11 UTC, Gauravi-S commented on src/app/authentication/commons/constants/routes.go
> +	CustomerchangepasswordEndpoint = "/changepassword"
rename endpoint to change-password.

2024-04-26 12:15 UTC, Gauravi-S commented on src/app/authentication/utils/validation.go
> +		hasSpecial = regexp.MustCompile(`[^a-zA-Z0-9]`).MatchString
It will be better if you can combine more than 1 regex together.

2024-04-26 12:17 UTC, Gauravi-S commented on src/app/authentication/business/changePasswordService.go
> +	utils.ValidatePassword(request.OldPassword)
No need to validate old password.
you should validate new password

2024-04-29 04:47 UTC, vipin-raj-coditas commented on src/models/claimsModel.go
Create a Token Model in genericModel ratherthan creating a claimsModel.go.

2024-04-29 04:49 UTC, vipin-raj-coditas commented on src/models/claimsModel.go
> +}
Remove this

2024-04-29 11:50 UTC, suman-byakod commented on .vscode/launch.json
> +}
don't change this file, keep as it is

2024-04-29 11:52 UTC, suman-byakod commented on src/app/authentication/models/changePasswordModel.go
> +	NewPassword string `json:"newPassword" validate:"required,min=8" example:"newPassword"`
Register the custom validation function and use the tag here

2024-04-29 11:53 UTC, suman-byakod commented on src/app/authentication/models/changePasswordModel.go
> +	NewPassword string `json:"newPassword" validate:"required,min=8" example:"newPassword"`
Add the valid example for both fields

2024-05-03 09:19 UTC, Gauravi-S commented on src/app/authentication/commons/constants/constants.go
> +)
it's already defined in genericConstants use that.

2024-05-03 09:22 UTC, Gauravi-S commented on src/app/authentication/commons/constants/routes.go
> +    ChangePassword = "/change-password"
correct the indentation

2024-05-03 09:24 UTC, Gauravi-S commented on src/app/authentication/commons/constants/errors.go
> +// changepassword errors
change comment to 
// authentication errors

2024-05-03 09:25 UTC, Gauravi-S commented on src/app/authentication/models/changePasswordModel.go
> +	NewPassword string `json:"" validate:"required,min=8,max=20,PasswordValidation" example:"Coditas@18"`
can keep as json:"-" for field which are not required

2024-05-03 09:26 UTC, Gauravi-S commented on src/app/authentication/repositories/changePasswordRepository.go
> +	if err := userRepository.db.Model(&models.Users{}).Where(constants.UserName, PasswordUpdateSQLCondition[constants.UserName]).Updates(PasswordUpdateSQLCondition).Count(&count).Error; err != nil {
take column name from genericConstants

2024-05-03 09:27 UTC, Gauravi-S commented on src/app/authentication/business/changePasswordService.go
> +func NewRestPasswordService(changePasswordInstance repositories.ChangePasswordRepositor) *ChangePassword {
rename function to NewChangePasswordService

2024-05-03 09:36 UTC, Gauravi-S commented on src/app/authentication/commons/constants/constants.go
> +	ServiceName      = "Authentication"
don't change this

2024-05-03 09:45 UTC, Gauravi-S commented on src/app/authentication/commons/constants/constants.go
> +	StatusKey                    = "Status"
why is this needed?

2024-05-03 10:02 UTC, vipin-raj-coditas requested changes

2024-05-03 10:02 UTC, vipin-raj-coditas commented on src/middleware/headerCheck/headerCheck.go
> +
take secret key from config/application.yml

2024-05-07 04:53 UTC, Gauravi-S commented on src/app/authentication/repositories/validateOTPRepository.go
> +	UpdateUserToken(userid, token string) error
keep variable name as userID everywhere.

2024-05-07 04:56 UTC, Gauravi-S commented on src/models/genericModels.go
> +type TokenModel struct {
rename this to TokenModel

2024-05-07 05:25 UTC, Gauravi-S commented on src/app/authentication/repositories/changePasswordRepository.go
> +type ChangePasswordRepositor interface {
rename to  ChangePasswordRepository

2024-05-07 05:26 UTC, Gauravi-S commented on src/app/authentication/handler/changePasswordHandler.go
> +type ControllerChangePassword struct {
keep name as ChangePasswordController

2024-05-07 05:41 UTC, merged